config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
    resources :management, only: [:index]
  end

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations'
    }

    # homes
    root to: 'posts#index'
    get 'homes/about', to: 'homes#about', as: :about

    # users
    get 'mypage/:id' => 'users#mypage', as: :mypage
    get 'mypage/:id/edit' => 'users#edit', as: :edit
    get 'mypage/:id/place' => 'users#mypage_place', as: :mypage_place
    get 'mypage/:id/post_index' => 'users#post_index', as: :post_index

    resource :users, only: [] do
      delete :withdraw, on: :collection
    end

    # post
    # resources :posts, only:[:new, :index, :show, :create, :edit, :update, :destroy] ,defaults: { format: 'json' } do
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      # comment
      resources :comments, only: [:create, :destroy]
      resource :places, only: [:new, :create, :update, :edit]
      resource :tags, only: [:create]

      member do
        patch :publish
      end
    end

    # search
    get 'search/result' => 'searches#search'

    resources :maps, only: [:show]

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :places, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :post_prefectures, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  enum season: { 春: 0, 夏: 1, 秋: 2, 冬: 3 }
  enum place: { 海外旅行: 0, 国内旅行: 1 }
  enum stay_nights: { '1泊': 0, '2泊': 1, '3泊': 2, '4泊': 3, '5泊': 4, '6泊以上': 5 }
  enum people: { '1人': 0, '2人': 1, '3人': 2, '4人': 3, '5人': 4, '6人以上': 5 }

  def self.looks(params)
    # 部分一致
    post = Post.where("title LIKE?", "%#{params[:searchdata]}%")
    # 旅行月
    post = post.where(travelmonth: params[:travel_months]) unless params[:travel_months].nil?

    # 都道府県名
    post = post.joins(:post_prefectures).where(post_prefectures: { prefecture: params[:prefectures] }) unless params[:prefectures] == "all_prefectures"

    # 宿泊日数フィルター
    post = post.where(night: params[:stay_nights]) unless params[:stay_nights] == "all_stay_nights"

    # 人数フィルター
    post = post.where(people: params[:people]) unless params[:people] == "all_people"

    # 投稿月
    unless params[:post_months].nil?
      if Rails.env.development?
        # 開発環境用
        # 月を2桁形式に整形する
        formatted_months = params[:post_months].map { |m| format('%02d', m) }

        # SQLiteの場合、created_atの月と比較する
        post = post.where("strftime('%m', posts.created_at) IN (?)", formatted_months)
      elsif Rails.env.production?
        # 本番環境用
        post = post.where("EXTRACT(MONTH FROM posts.created_at) IN (?)", params[:post_months])
      end
    end

    # 観光点数
    post = post.where(good: params[:travel_goods]) unless params[:travel_goods].nil?

    post
  end

  def get_target_place(place_id)
    place_id ? places.find(target_place_id) : places.first
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_management_index_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_good.html.erb
<div id="star_comment_<%= category %>_<%= data.id %>"></div>
<script>
  var elem = document.querySelector("#star_<%= category %>_show_<%= data.id %>");
  elem.innerHTML = ""
  var option = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    readOnly: true,
    <% if data.good.present? %>
        score: <%= data.good %>
      <% else %>
        score: 0
    <% end %>
  };
  raty(elem, option);
</script>

app/views/admin/posts/_index.html.erb
<div class="col p-0 bg-white" data-management-target="post">
  <table class="table">
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">投稿者名</th>
      <th scope="col">削除ボタン</th>
    </tr>
    <tbody>
      <% postall.each do | post |%>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.user.name %></td>
          <td><%= link_to "削除" , admin_post_path(post.id),method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"}%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table">
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">投稿者名</th>
        </tr>
        <tbody>
          <% @post.each do |post| %>
            <tr>
            <td><%= link_to post.title ,admin_post_path(post.id) %></td>
            <td><%= post.user.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="h3">
      <%= @post.title %>
    </div>
  </div>
  <div class="row">
     <%= @post.body %>
  </div>
  <div class="row">
    <% render "admin/posts/good.html.erb", category: "post" , data: @post %>
  </div>

  <div class="row">
  <% @post.comments.each do |comment|%>
    <%= comment.comment %><br />
    <% render "admin/posts/good.html.erb", category: "comment" , data: comment %>
    <%= comment.user.name %>
    <%= link_to "Comment削除", admin_comment_path(comment.id), method: :delete, data: {confirm: "削除しますか？"} %>
  <% end %>
  </div>
  <div class="row">
    <%= link_to "Post削除", admin_post_path(@post.id), method: :delete, data: {confirm: "削除しますか？"} %>
  </div>
</div>