config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    resources :users, only: [:show, :destroy]
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
    resources :management, only: [:index]
  end

  scope module: :public do
    devise_for :users, controllers: {
      registrations: 'public/registrations'
    }

    # homes
    root to: 'posts#index'
    get 'homes/about', to: 'homes#about', as: :about

    # users
    get 'mypage/:id' => 'users#mypage', as: :mypage
    get 'mypage/:id/edit' => 'users#edit', as: :edit
    get 'mypage/:id/place' => 'users#mypage_place', as: :mypage_place
    get 'mypage/:id/post_index' => 'users#post_index', as: :post_index

    resource :users, only: [] do
      delete :withdraw, on: :collection
    end

    # post
    # resources :posts, only:[:new, :index, :show, :create, :edit, :update, :destroy] ,defaults: { format: 'json' } do
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      # comment
      resources :comments, only: [:create, :destroy]
      resource :places, only: [:new, :create, :update, :edit]
      resource :tags, only: [:create]

      member do
        patch :publish
      end
    end

    # search
    get 'search/result' => 'searches#search'

    resources :maps, only: [:show]

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="d-flex align-items-center me-auto">
        <%= link_to root_path,class: "nav-link text-light" do %>
          <%= image_tag asset_path('travelog_logo.png'),size: "170x50"%>
        <% end %>
      </div>
      <div class="d-flex justify-content-center flex-grow-1">
        <ul class="navbar-nav" style="margin-left: 30%">
          <div class="nav-item">
            <%= render 'public/searches/search.html.erb' %>
          </div>
        </ul>
      </div>
      <div class="d-flex align-items-center ms-auto">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to about_path, class: "btn text-light" do %>
              Travelogとは
            <% end %>
          </li>
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete,class: "nav-link text-light" do %>
                ログアウト
              <% end %>
            </li>
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to mypage_path(current_user.id) , class: "btn btn-info" do %>
                マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path , class: "btn btn-info" do %>
                新規投稿
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path , method: :delete, class: "btn btn-danger" do %>
                ログアウト
              <% end %>
            </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "btn btn-success" do %>
                  会員登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "btn btn-primary"  do %>
                  ログイン
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <header>
      <% breadcrumb_content = breadcrumbs(separator: " &rsaquo; ") %>
      <% if breadcrumb_content.present? %>
      <nav aria-label="breadcrumb" class="breadcrumb-wrapper">
        <ol class="breadcrumb">
          <%= breadcrumb_content %>
        </ol>
      </nav>
      <% end %>
    </header>
    <main class="pb-5" style="background-image: url('<%= asset_path('okumono_no9.png') %>'); background-color:rgba(255,255,255,0.5); background-blend-mode:lighten;">
      <%= yield %>
    </main>
    <footer>
      <div class="container-fluid footer p-3">
        <div class="text-center text-white">
          Copyright © Travelog All Rights Reserved.
        </div>
      </div>
    </footer>
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <% key = "error" if key == "alert" %>
        <% key = "success" if key == "notice" %>
        <script>
          toastr['<%= key %>']('<%= value %>');
        </script>
      <% end %>
    <% end %>
  </body>
</html>